-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black rplugin/
        language: system
        types: [python]
    -   id: pylint
        name: pylint
        entry: poetry run pylint rplugin/python3/nvim_diary_template -j 0 -d W0511
        language: system
        types: [python]